# Generated by Django 5.0.6 on 2024-05-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('provincia', models.IntegerField(choices=[(0, 'Mendoza'), (1, 'San Luis'), (2, 'San Juan'), (3, 'La Rioja'), (4, 'Neuquen')])),
            ],
        ),
    ]
